apiVersion: apps/v1
kind: Deployment
metadata:
  name: logk8s
  namespace: logk8s
  labels:
    name: listene
spec:
  replicas: 1
  selector:
    matchLabels:
      app: listener
  template:
    metadata:
      labels:
        app: listener
    spec:
      containers:
      - name: listener
        image: logk8s/listener:1.0
        ports:
        - containerPort: 5000
          name: grpc
        - containerPort: 3000
          name: websocket
